# Generated by Django 2.2.3 on 2019-07-28 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('org_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(max_length=255)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdorgs',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('group_name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups',
                                                   to='organization.Organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createdgroups',
                                           to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UsertoOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('admin',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_user_organizations',
                                   to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertoorgs',
                                          to='organization.Organization')),
                ('user_obj',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorganizations',
                                   to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_obj', 'org')},
            },
        ),
        migrations.CreateModel(
            name='UsertoGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_user_groups',
                                            to=settings.AUTH_USER_MODEL)),
                ('grp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertogroups',
                                          to='organization.Groups')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertoorgtogroups',
                                          to='organization.Organization')),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usergroups',
                                               to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_obj', 'org', 'grp')},
            },
        ),
    ]
