# Generated by Django 2.2.3 on 2019-08-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='group_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
