# Generated by Django 2.2.3 on 2019-07-26 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertogroups',
            old_name='user',
            new_name='user_obj',
        ),
        migrations.RenameField(
            model_name='usertoorg',
            old_name='user',
            new_name='user_obj',
        ),
        migrations.AddField(
            model_name='usertogroups',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_user_groups', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertoorg',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='add_user_organizations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usertogroups',
            unique_together={('user_obj', 'org', 'grp')},
        ),
        migrations.AlterUniqueTogether(
            name='usertoorg',
            unique_together={('user_obj', 'org')},
        ),
    ]
