# Generated by Django 2.2.3 on 2019-08-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20190815_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='hasPrivilege',
            field=models.BooleanField(default=False),
        ),
    ]
