# Generated by Django 2.2.3 on 2019-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.CharField(max_length=255),
        ),
    ]
