# Generated by Django 2.2.3 on 2019-08-01 16:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20190729_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='fields',
        ),
        migrations.AddField(
            model_name='form',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
