# Generated by Django 2.2.3 on 2019-08-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_auto_20190729_0250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='link',
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='filename',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
