# Generated by Django 2.2.3 on 2019-08-07 09:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_auto_20190803_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='fields',
        ),
        migrations.AddField(
            model_name='form',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='form',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='response',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
