# Generated by Django 2.2.3 on 2019-08-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20190807_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
