# Generated by Django 2.2.3 on 2019-08-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_stage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.IntegerField(),
        ),
    ]
