# Generated by Django 2.2.3 on 2019-07-24 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('process', '0007_auto_20190721_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stage',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='users',
        ),
        migrations.AddField(
            model_name='process',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stage',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='groups',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to_group', to='organization.Groups'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_name',
            field=models.CharField(max_length=255),
        ),
    ]
